### ISSUE TITLE
cmd support for packing/unpacking ubiart ipk archives

### ISSUE THREAD

**Issue by smpial** [RayCarrot/RaymanControlPanel#4]
Hello! Can you make a packing/unpacking ubiart ipk archives support with cmd line?

**Comment by RayCarrot** [comment]
I previously answered this in #1. I have since added some basic command-line arguments as a test, but this is not a command-line app and the functionality in it is made for the app's UI. On one hand it would be possible utilizing the same methods as the Archive Explorer uses to directly extract to or repack from a folder, but you'd also need to be able to specify the archive settings in text form then rather than using the auto-populated drop-down in the UI which complicates matters. It would probably also be easier for such a purpose to create a new tool rather than using this one since it kind of defeats to purpose of what this is for. The essential parts for working with the IPK files are in the [UbiArt library](https://github.com/BinarySerializer/BinarySerializer.UbiArt/tree/main/src/DataTypes/Bundle) and [here](https://github.com/RayCarrot/RayCarrot.RCP.Metro/blob/master/src/RayCarrot.RCP.Metro/Archive/Manager/UbiArt_Ipk/UbiArtIPKArchiveDataManager.cs).

**Comment by Bezdrom** [comment]
Hello. Can't use Rayman Control Panel from the cmd line? (example: specify the category we need, select what we need, specify the path to it)
